const keys = {
    REACT_APP_OPENAI_API_KEY: "BLAH",
    REACT_APP_OPENAI_URL: "BLAH",
    REACT_APP_FIREBASE_API_KEY: "BLAH",
    REACT_APP_STRIPE_PUBLIC_KEY: "BLAH",
    REACT_APP_PROD_URL: "BLAH",
    REACT_APP_RECAPTCHA_SITE_KEY: "BLAH",
    REACT_APP_UPDATE_QUERY_LIMIT_URL: "BLAH",
    REACT_APP_BILLING_PORTAL_URL: "BLAH",
    REACT_APP_GET_CUSTOMER_URL: "BLAH",
    REACT_APP_GET_SUBSCRIPTION_URL: "BLAH",
    REACT_APP_POST_TASK_DATA_URL: "BLAH",
    REACT_APP_GET_PRODUCTS_URL: "BLAH", 
    REACT_APP_STREAM_ASSISTANT_RESPONSE_URL: "BLAH"
}

export default keys