import keys from '../keys'
import db, { provider, analytics, auth } from './firebase'

const config = { REACT_APP_OPENAI_API_KEY: '', REACT_APP_OPENAI_URL: '', db, provider, analytics, auth, REACT_APP_RECAPTCHA_SITE_KEY: '', REACT_APP_RECAPTCHA_SECRET_KEY: '', REACT_APP_STRIPE_PUBLIC_KEY: '', REACT_APP_STRIPE_SECRET_KEY: '', REACT_APP_FIREBASE_API_KEY: '' }

config.REACT_APP_PROD_URL = `${keys.REACT_APP_PROD_URL}`
config.REACT_APP_FIREBASE_API_KEY = keys.REACT_APP_FIREBASE_API_KEY
config.REACT_APP_OPENAI_API_KEY = keys.REACT_APP_OPENAI_API_KEY
config.REACT_APP_OPENAI_URL = keys.REACT_APP_OPENAI_URL
config.REACT_APP_RECAPTCHA_SITE_KEY = keys.REACT_APP_RECAPTCHA_SITE_KEY
config.REACT_APP_RECAPTCHA_SECRET_KEY = keys.REACT_APP_RECAPTCHA_SECRET_KEY
config.REACT_APP_STRIPE_PUBLIC_KEY = keys.REACT_APP_STRIPE_PUBLIC_KEY
config.REACT_APP_STRIPE_SECRET_KEY = keys.REACT_APP_STRIPE_SECRET_KEY
// }

export default config